version: "2"

services:
  todo-server:
    image: till/jtodo

  todo-spec:
    image: till/todo-spec
    volumes:
      - /app

  integration-test:
    build: .
    environment:
      - TODO_SERVER_URL=http://todo-server:9884
    links:
      - todo-server
    volumes_from:
      - todo-spec
    command: bash -c "bundle install && bundle exec cucumber"
