version: "2"
services:
  todo-server:
    image: till/jtodo

  todo-spec:
    image: till/todo-spec
    volumes:
      - /spec
    command: /bin/sh

  test:
    build: .
    environment:
      - TODO_SERVER_URL=http://todo-server:9884
    links:
      - todo-server
    volumes_from:
      - todo-spec
    working_dir: /spec
    command: bash -c "bundle install && bundle exec cucumber"
